/**
 * Tragency V3 Seed — Real visa-sponsoring companies, jobs & news
 * Run: node server/seed-v3.js
 */
require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const { query, pool } = require('./db');

async function seed() {
  console.log('🌱 Seeding V3 data (companies, jobs, news)…\n');

  try {
    // ═══════════════════════════════════════════════════════════════════════════
    //  COMPANIES
    // ═══════════════════════════════════════════════════════════════════════════

    const companiesData = [
      // ── UK (Skilled Worker) ──────────────────────────────────────────────────
      { name: 'NHS', country: 'United Kingdom', industry: 'Healthcare', website: 'https://www.jobs.nhs.uk', description: 'The National Health Service is the publicly funded healthcare system in England, employing over 1.3 million staff.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'Deloitte UK', country: 'United Kingdom', industry: 'Consulting', website: 'https://www2.deloitte.com/uk/en/careers.html', description: 'Deloitte is a leading global professional services firm providing audit, consulting, tax and advisory services.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'PwC UK', country: 'United Kingdom', industry: 'Consulting', website: 'https://www.pwc.co.uk/careers.html', description: 'PricewaterhouseCoopers is one of the Big Four accounting firms offering assurance, tax and consulting services.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'KPMG UK', country: 'United Kingdom', industry: 'Consulting', website: 'https://home.kpmg/uk/en/home/careers.html', description: 'KPMG is a multinational professional services network and one of the Big Four accounting organisations.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'EY UK', country: 'United Kingdom', industry: 'Consulting', website: 'https://www.ey.com/en_uk/careers', description: 'Ernst & Young is a global leader in assurance, tax, transaction and advisory services.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'Google UK', country: 'United Kingdom', industry: 'Technology', website: 'https://careers.google.com/locations/london/', description: 'Google UK is the British arm of the technology giant, headquartered at their King\'s Cross campus in London.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'Amazon UK', country: 'United Kingdom', industry: 'Technology', website: 'https://www.amazon.jobs/en-gb/', description: 'Amazon UK operates e-commerce, cloud computing, and logistics across the United Kingdom.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'Microsoft UK', country: 'United Kingdom', industry: 'Technology', website: 'https://careers.microsoft.com', description: 'Microsoft UK is the British subsidiary of the global technology corporation based in Reading.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'Meta UK', country: 'United Kingdom', industry: 'Technology', website: 'https://www.metacareers.com', description: 'Meta UK houses one of the company\'s largest engineering hubs outside the US, based in London.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'Accenture UK', country: 'United Kingdom', industry: 'Consulting', website: 'https://www.accenture.com/gb-en/careers', description: 'Accenture is a global professional services company specialising in IT services and consulting.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'Barclays', country: 'United Kingdom', industry: 'Finance', website: 'https://home.barclays/careers/', description: 'Barclays is a British universal bank offering retail, wholesale, and investment banking services worldwide.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'HSBC', country: 'United Kingdom', industry: 'Finance', website: 'https://www.hsbc.com/careers', description: 'HSBC is one of the world\'s largest banking and financial services organisations, headquartered in London.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'JP Morgan London', country: 'United Kingdom', industry: 'Finance', website: 'https://careers.jpmorgan.com', description: 'JP Morgan\'s London office is a major hub for investment banking and asset management in Europe.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'Goldman Sachs London', country: 'United Kingdom', industry: 'Finance', website: 'https://www.goldmansachs.com/careers/', description: 'Goldman Sachs London is one of the firm\'s largest offices outside New York, specialising in securities and investment management.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'McKinsey London', country: 'United Kingdom', industry: 'Consulting', website: 'https://www.mckinsey.com/careers', description: 'McKinsey & Company London is a leading global management consulting firm advising top corporations and governments.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'BCG London', country: 'United Kingdom', industry: 'Consulting', website: 'https://careers.bcg.com', description: 'Boston Consulting Group London provides management consulting services to leading businesses and institutions.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'Unilever UK', country: 'United Kingdom', industry: 'Retail', website: 'https://careers.unilever.com', description: 'Unilever is a British multinational consumer goods company with products sold in over 190 countries.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'GSK', country: 'United Kingdom', industry: 'Healthcare', website: 'https://www.gsk.com/en-gb/careers/', description: 'GlaxoSmithKline is a British pharmaceutical company and one of the world\'s largest healthcare firms.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'AstraZeneca', country: 'United Kingdom', industry: 'Healthcare', website: 'https://careers.astrazeneca.com', description: 'AstraZeneca is a British-Swedish multinational pharmaceutical and biotechnology company headquartered in Cambridge.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'Rolls Royce', country: 'United Kingdom', industry: 'Aerospace', website: 'https://careers.rolls-royce.com', description: 'Rolls-Royce Holdings is a British multinational aerospace and defence company producing aircraft engines and power systems.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'BAE Systems', country: 'United Kingdom', industry: 'Aerospace', website: 'https://www.baesystems.com/en/careers', description: 'BAE Systems is a British multinational arms, security and aerospace company headquartered in London.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'BT Group', country: 'United Kingdom', industry: 'Telecom', website: 'https://www.bt.com/careers', description: 'BT Group is the UK\'s leading telecommunications company providing broadband and mobile services.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'Vodafone', country: 'United Kingdom', industry: 'Telecom', website: 'https://careers.vodafone.com', description: 'Vodafone is one of the world\'s largest telecommunications companies, headquartered in Newbury, UK.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: 'Tesco', country: 'United Kingdom', industry: 'Retail', website: 'https://www.tesco-careers.com', description: 'Tesco is the UK\'s largest supermarket chain and one of the world\'s largest retailers by revenue.', size: 'enterprise', visa_types: ['Skilled Worker'] },
      { name: "Sainsbury's", country: 'United Kingdom', industry: 'Retail', website: 'https://sainsburys.jobs', description: "Sainsbury's is the second-largest chain of supermarkets in the United Kingdom.", size: 'enterprise', visa_types: ['Skilled Worker'] },

      // ── USA (H-1B, L-1) ──────────────────────────────────────────────────────
      { name: 'Google', country: 'United States', industry: 'Technology', website: 'https://careers.google.com', description: 'Google is a multinational technology company specialising in search, cloud computing, and artificial intelligence.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Microsoft', country: 'United States', industry: 'Technology', website: 'https://careers.microsoft.com', description: 'Microsoft is the world\'s leading software company, known for Windows, Azure, and Office products.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Amazon', country: 'United States', industry: 'Technology', website: 'https://www.amazon.jobs', description: 'Amazon is the world\'s largest e-commerce and cloud computing company headquartered in Seattle.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Meta', country: 'United States', industry: 'Technology', website: 'https://www.metacareers.com', description: 'Meta Platforms operates Facebook, Instagram, and WhatsApp, and is investing heavily in the metaverse.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Apple', country: 'United States', industry: 'Technology', website: 'https://www.apple.com/careers/', description: 'Apple is a global technology leader known for the iPhone, Mac, and innovative consumer electronics.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Netflix', country: 'United States', industry: 'Technology', website: 'https://jobs.netflix.com', description: 'Netflix is the world\'s leading streaming entertainment service with over 230 million subscribers globally.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Tesla', country: 'United States', industry: 'Automotive', website: 'https://www.tesla.com/careers', description: 'Tesla is an electric vehicle and clean energy company founded by Elon Musk, based in Austin, Texas.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Uber', country: 'United States', industry: 'Technology', website: 'https://www.uber.com/us/en/careers/', description: 'Uber Technologies is a ride-hailing and food delivery platform operating in over 70 countries.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Airbnb', country: 'United States', industry: 'Technology', website: 'https://careers.airbnb.com', description: 'Airbnb is the world\'s largest online marketplace for lodging and tourism experiences.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Salesforce', country: 'United States', industry: 'Technology', website: 'https://www.salesforce.com/company/careers/', description: 'Salesforce is the world\'s leading customer relationship management platform and enterprise cloud provider.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Oracle', country: 'United States', industry: 'Technology', website: 'https://www.oracle.com/careers/', description: 'Oracle Corporation is a multinational technology company specialising in database software and cloud solutions.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'IBM', country: 'United States', industry: 'Technology', website: 'https://www.ibm.com/careers/', description: 'IBM is a global technology and consulting company with expertise in AI, cloud, and enterprise solutions.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Intel', country: 'United States', industry: 'Technology', website: 'https://www.intel.com/content/www/us/en/jobs/jobs-at-intel.html', description: 'Intel is the world\'s largest semiconductor chip manufacturer and a leader in computing innovation.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Cisco', country: 'United States', industry: 'Technology', website: 'https://jobs.cisco.com', description: 'Cisco Systems is a global leader in networking hardware, software, and cybersecurity solutions.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Adobe', country: 'United States', industry: 'Technology', website: 'https://www.adobe.com/careers.html', description: 'Adobe is a creative software giant known for Photoshop, Illustrator, and the Creative Cloud suite.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'VMware', country: 'United States', industry: 'Technology', website: 'https://careers.vmware.com', description: 'VMware is a leading provider of cloud computing and virtualisation software and services.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'PayPal', country: 'United States', industry: 'Finance', website: 'https://careers.pypl.com', description: 'PayPal is a global fintech company operating the world\'s most widely used online payment system.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Stripe', country: 'United States', industry: 'Finance', website: 'https://stripe.com/jobs', description: 'Stripe is a financial technology company that builds economic infrastructure for the internet.', size: 'mid', visa_types: ['H-1B', 'L-1'] },
      { name: 'Goldman Sachs', country: 'United States', industry: 'Finance', website: 'https://www.goldmansachs.com/careers/', description: 'Goldman Sachs is a leading global investment banking, securities, and investment management firm.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'JP Morgan', country: 'United States', industry: 'Finance', website: 'https://careers.jpmorgan.com', description: 'JPMorgan Chase is the largest bank in the United States by assets and a leading global financial institution.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Morgan Stanley', country: 'United States', industry: 'Finance', website: 'https://www.morganstanley.com/careers', description: 'Morgan Stanley is a leading global financial services firm providing investment banking and wealth management.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'McKinsey', country: 'United States', industry: 'Consulting', website: 'https://www.mckinsey.com/careers', description: 'McKinsey & Company is the world\'s most prestigious management consulting firm, advising Fortune 500 companies.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'BCG', country: 'United States', industry: 'Consulting', website: 'https://careers.bcg.com', description: 'Boston Consulting Group is one of the top three management consulting firms globally.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Bain', country: 'United States', industry: 'Consulting', website: 'https://www.bain.com/careers/', description: 'Bain & Company is an elite management consulting firm known for results delivery and private equity work.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },
      { name: 'Deloitte US', country: 'United States', industry: 'Consulting', website: 'https://www2.deloitte.com/us/en/careers.html', description: 'Deloitte US is the largest professional services firm in the United States by revenue.', size: 'enterprise', visa_types: ['H-1B', 'L-1'] },

      // ── Canada (LMIA, Global Talent) ─────────────────────────────────────────
      { name: 'Shopify', country: 'Canada', industry: 'Technology', website: 'https://www.shopify.com/careers', description: 'Shopify is a Canadian e-commerce platform that powers over 2 million businesses worldwide.', size: 'enterprise', visa_types: ['LMIA', 'Global Talent'] },
      { name: 'RBC', country: 'Canada', industry: 'Finance', website: 'https://jobs.rbc.com', description: 'Royal Bank of Canada is the largest bank in Canada by market capitalisation and assets.', size: 'enterprise', visa_types: ['LMIA', 'Global Talent'] },
      { name: 'TD Bank', country: 'Canada', industry: 'Finance', website: 'https://jobs.td.com', description: 'TD Bank Group is one of Canada\'s largest financial institutions with operations across North America.', size: 'enterprise', visa_types: ['LMIA', 'Global Talent'] },
      { name: 'Scotiabank', country: 'Canada', industry: 'Finance', website: 'https://www.scotiabank.com/careers', description: 'Scotiabank is Canada\'s most international bank with operations in over 30 countries.', size: 'enterprise', visa_types: ['LMIA', 'Global Talent'] },
      { name: 'Rogers', country: 'Canada', industry: 'Telecom', website: 'https://about.rogers.com/careers/', description: 'Rogers Communications is a leading Canadian telecommunications and media company.', size: 'enterprise', visa_types: ['LMIA', 'Global Talent'] },
      { name: 'Bell', country: 'Canada', industry: 'Telecom', website: 'https://jobs.bell.ca', description: 'Bell Canada is the country\'s largest telecommunications company providing wireless, internet, and TV services.', size: 'enterprise', visa_types: ['LMIA', 'Global Talent'] },
      { name: 'Amazon Canada', country: 'Canada', industry: 'Technology', website: 'https://www.amazon.jobs/en/locations/canada', description: 'Amazon Canada operates major fulfillment centres and a growing tech hub in Vancouver and Toronto.', size: 'enterprise', visa_types: ['LMIA', 'Global Talent'] },
      { name: 'Google Canada', country: 'Canada', industry: 'Technology', website: 'https://careers.google.com/locations/waterloo/', description: 'Google Canada has engineering offices in Waterloo, Toronto, and Montreal working on core products.', size: 'enterprise', visa_types: ['LMIA', 'Global Talent'] },
      { name: 'Microsoft Canada', country: 'Canada', industry: 'Technology', website: 'https://careers.microsoft.com', description: 'Microsoft Canada has a major development centre in Vancouver and offices across the country.', size: 'enterprise', visa_types: ['LMIA', 'Global Talent'] },
      { name: 'Bombardier', country: 'Canada', industry: 'Aerospace', website: 'https://bombardier.com/en/careers', description: 'Bombardier is a Canadian multinational aerospace company and the world\'s third-largest aircraft manufacturer.', size: 'enterprise', visa_types: ['LMIA', 'Global Talent'] },

      // ── Germany (EU Blue Card) ───────────────────────────────────────────────
      { name: 'SAP', country: 'Germany', industry: 'Technology', website: 'https://jobs.sap.com', description: 'SAP is Europe\'s largest software company and the world leader in enterprise application software.', size: 'enterprise', visa_types: ['EU Blue Card'] },
      { name: 'Siemens', country: 'Germany', industry: 'Technology', website: 'https://jobs.siemens.com', description: 'Siemens is a German multinational conglomerate and Europe\'s largest industrial manufacturing company.', size: 'enterprise', visa_types: ['EU Blue Card'] },
      { name: 'BMW', country: 'Germany', industry: 'Automotive', website: 'https://www.bmwgroup.jobs', description: 'BMW is a German luxury automobile manufacturer and one of the world\'s leading premium car brands.', size: 'enterprise', visa_types: ['EU Blue Card'] },
      { name: 'Bosch', country: 'Germany', industry: 'Technology', website: 'https://www.bosch.com/careers/', description: 'Robert Bosch GmbH is a German engineering and technology company and the world\'s largest automotive parts supplier.', size: 'enterprise', visa_types: ['EU Blue Card'] },
      { name: 'Mercedes-Benz', country: 'Germany', industry: 'Automotive', website: 'https://group.mercedes-benz.com/careers/', description: 'Mercedes-Benz is a German global automobile manufacturer and one of the most recognised luxury car brands.', size: 'enterprise', visa_types: ['EU Blue Card'] },
      { name: 'Deutsche Bank', country: 'Germany', industry: 'Finance', website: 'https://careers.db.com', description: 'Deutsche Bank is Germany\'s largest bank and a leading global investment bank headquartered in Frankfurt.', size: 'enterprise', visa_types: ['EU Blue Card'] },
      { name: 'Allianz', country: 'Germany', industry: 'Finance', website: 'https://careers.allianz.com', description: 'Allianz is the world\'s largest insurance company by revenue, headquartered in Munich.', size: 'enterprise', visa_types: ['EU Blue Card'] },
      { name: 'Volkswagen', country: 'Germany', industry: 'Automotive', website: 'https://www.volkswagen-karriere.de', description: 'Volkswagen is the world\'s largest automaker by sales and Germany\'s biggest company by revenue.', size: 'enterprise', visa_types: ['EU Blue Card'] },
      { name: 'Bayer', country: 'Germany', industry: 'Healthcare', website: 'https://career.bayer.com', description: 'Bayer is a German multinational pharmaceutical and life sciences company with a 160-year history.', size: 'enterprise', visa_types: ['EU Blue Card'] },
      { name: 'BASF', country: 'Germany', industry: 'Energy', website: 'https://www.basf.com/global/en/careers.html', description: 'BASF is the world\'s largest chemical producer and a key player in materials, chemicals, and industrial solutions.', size: 'enterprise', visa_types: ['EU Blue Card'] },

      // ── Australia (482 Visa, 494 Visa) ───────────────────────────────────────
      { name: 'BHP', country: 'Australia', industry: 'Mining', website: 'https://www.bhp.com/careers', description: 'BHP is the world\'s largest mining company by market capitalisation, headquartered in Melbourne.', size: 'enterprise', visa_types: ['482 Visa', '494 Visa'] },
      { name: 'Rio Tinto', country: 'Australia', industry: 'Mining', website: 'https://www.riotinto.com/careers', description: 'Rio Tinto is a global mining group and the world\'s second-largest metals and mining corporation.', size: 'enterprise', visa_types: ['482 Visa', '494 Visa'] },
      { name: 'Commonwealth Bank', country: 'Australia', industry: 'Finance', website: 'https://www.commbank.com.au/about-us/careers.html', description: 'Commonwealth Bank is Australia\'s largest bank by market capitalisation and number of customers.', size: 'enterprise', visa_types: ['482 Visa', '494 Visa'] },
      { name: 'Atlassian', country: 'Australia', industry: 'Technology', website: 'https://www.atlassian.com/company/careers', description: 'Atlassian is an Australian enterprise software company known for Jira, Confluence, and Trello.', size: 'enterprise', visa_types: ['482 Visa', '494 Visa'] },
      { name: 'Canva', country: 'Australia', industry: 'Technology', website: 'https://www.canva.com/careers/', description: 'Canva is an Australian graphic design platform valued at over $25 billion with 150 million monthly users.', size: 'mid', visa_types: ['482 Visa', '494 Visa'] },
      { name: 'Telstra', country: 'Australia', industry: 'Telecom', website: 'https://www.telstra.com.au/careers', description: 'Telstra is Australia\'s largest telecommunications company providing mobile, internet, and enterprise services.', size: 'enterprise', visa_types: ['482 Visa', '494 Visa'] },
      { name: 'Woolworths', country: 'Australia', industry: 'Retail', website: 'https://www.wowcareers.com.au', description: 'Woolworths Group is Australia\'s largest retailer and one of the largest food retailers globally.', size: 'enterprise', visa_types: ['482 Visa', '494 Visa'] },
      { name: 'ANZ Bank', country: 'Australia', industry: 'Finance', website: 'https://www.anz.com.au/careers/', description: 'ANZ Bank is one of Australia\'s four largest banks with significant operations in New Zealand and Asia.', size: 'enterprise', visa_types: ['482 Visa', '494 Visa'] },

      // ── UAE (Employment Visa) ────────────────────────────────────────────────
      { name: 'Emirates', country: 'United Arab Emirates', industry: 'Aerospace', website: 'https://www.emiratesgroupcareers.com', description: 'Emirates is the largest airline in the Middle East, operating over 3,600 flights per week from Dubai.', size: 'enterprise', visa_types: ['Employment Visa'] },
      { name: 'Etihad', country: 'United Arab Emirates', industry: 'Aerospace', website: 'https://www.etihad.com/en/careers', description: 'Etihad Airways is the national airline of the United Arab Emirates based in Abu Dhabi.', size: 'enterprise', visa_types: ['Employment Visa'] },
      { name: 'ADNOC', country: 'United Arab Emirates', industry: 'Energy', website: 'https://www.adnoc.ae/careers', description: 'Abu Dhabi National Oil Company is one of the world\'s largest oil and gas companies by production output.', size: 'enterprise', visa_types: ['Employment Visa'] },
      { name: 'Dubai Holding', country: 'United Arab Emirates', industry: 'Finance', website: 'https://www.dubaiholding.com/careers/', description: 'Dubai Holding is a global investment company with assets spanning real estate, hospitality, and technology.', size: 'enterprise', visa_types: ['Employment Visa'] },
      { name: 'Emaar', country: 'United Arab Emirates', industry: 'Finance', website: 'https://www.emaar.com/en/careers', description: 'Emaar Properties is the developer behind the Burj Khalifa and Dubai Mall, and a leader in global real estate.', size: 'enterprise', visa_types: ['Employment Visa'] },
      { name: 'Majid Al Futtaim', country: 'United Arab Emirates', industry: 'Retail', website: 'https://www.majidalfuttaim.com/en/careers', description: 'Majid Al Futtaim is the leading shopping mall, communities, and retail operator in the Middle East and Africa.', size: 'enterprise', visa_types: ['Employment Visa'] },
    ];

    // Insert companies and collect IDs by name
    const companyIds = {};

    for (const c of companiesData) {
      const { rows } = await query(`
        INSERT INTO companies (name, country, industry, website, description, size, sponsors_visa, visa_types)
        VALUES ($1, $2, $3, $4, $5, $6, TRUE, $7::jsonb)
        ON CONFLICT DO NOTHING
        RETURNING id, name
      `, [c.name, c.country, c.industry, c.website, c.description, c.size, JSON.stringify(c.visa_types)]);

      if (rows.length) {
        companyIds[c.name] = rows[0].id;
      } else {
        // already exists — fetch id
        const { rows: existing } = await query(
          `SELECT id FROM companies WHERE name = $1 AND country = $2 LIMIT 1`,
          [c.name, c.country]
        );
        if (existing.length) companyIds[c.name] = existing[0].id;
      }
    }

    console.log(`  ✓ ${Object.keys(companyIds).length} companies seeded`);

    // ═══════════════════════════════════════════════════════════════════════════
    //  JOBS
    // ═══════════════════════════════════════════════════════════════════════════

    const jobsData = [
      // ── UK Jobs ────────────────────────────────────────────────────────────
      { company: 'Google UK', title: 'Software Engineer', description: 'Design and build scalable distributed systems for Google Search. You will work on performance-critical backend services used by billions of users daily.', country: 'United Kingdom', city: 'London', industry: 'Technology', salary_min: 65000, salary_max: 110000, salary_currency: 'GBP', visa_type: 'Skilled Worker', experience_min: 2, qualification: 'bachelors', skills: ['Python', 'Go', 'Distributed Systems', 'Kubernetes'] },
      { company: 'NHS', title: 'Registered Nurse', description: 'Provide high-quality patient care in acute medical wards. The NHS offers international nurses a structured support programme including OSCE preparation and accommodation assistance.', country: 'United Kingdom', city: 'Manchester', industry: 'Healthcare', salary_min: 28400, salary_max: 34600, salary_currency: 'GBP', visa_type: 'Skilled Worker', experience_min: 1, qualification: 'bachelors', skills: ['Patient Care', 'Clinical Assessment', 'NMC Registration', 'Team Working'] },
      { company: 'NHS', title: 'Junior Doctor', description: 'Join the NHS as a Foundation Year doctor providing frontline patient care. International medical graduates are welcome and visa sponsorship is provided for eligible candidates.', country: 'United Kingdom', city: 'Birmingham', industry: 'Healthcare', salary_min: 32400, salary_max: 55300, salary_currency: 'GBP', visa_type: 'Skilled Worker', experience_min: 0, qualification: 'masters', skills: ['Clinical Medicine', 'Patient Assessment', 'GMC Registration', 'Communication'] },
      { company: 'Deloitte UK', title: 'Business Analyst', description: 'Work with major UK corporates to solve complex business challenges through data-driven insights. Deloitte provides a structured visa sponsorship pathway for international hires.', country: 'United Kingdom', city: 'London', industry: 'Consulting', salary_min: 35000, salary_max: 55000, salary_currency: 'GBP', visa_type: 'Skilled Worker', experience_min: 1, qualification: 'bachelors', skills: ['Data Analysis', 'SQL', 'PowerBI', 'Stakeholder Management'] },
      { company: 'Barclays', title: 'Financial Analyst', description: 'Analyse financial data and build models to support investment decisions in Barclays\' corporate banking division. You will collaborate with senior bankers on high-profile transactions.', country: 'United Kingdom', city: 'London', industry: 'Finance', salary_min: 40000, salary_max: 65000, salary_currency: 'GBP', visa_type: 'Skilled Worker', experience_min: 2, qualification: 'bachelors', skills: ['Financial Modelling', 'Excel', 'Bloomberg', 'CFA'] },
      { company: 'AstraZeneca', title: 'Pharmacist', description: 'Lead pharmaceutical development projects within AstraZeneca\'s R&D pipeline. You will ensure regulatory compliance and drive clinical trial processes for life-saving medicines.', country: 'United Kingdom', city: 'Cambridge', industry: 'Healthcare', salary_min: 45000, salary_max: 70000, salary_currency: 'GBP', visa_type: 'Skilled Worker', experience_min: 3, qualification: 'masters', skills: ['Pharmaceutical Sciences', 'GMP', 'Regulatory Affairs', 'Clinical Trials'] },
      { company: 'Rolls Royce', title: 'Mechanical Engineer', description: 'Design and optimise components for next-generation aircraft engines at Rolls-Royce. You will use advanced CAD and simulation tools to improve engine performance and fuel efficiency.', country: 'United Kingdom', city: 'Derby', industry: 'Aerospace', salary_min: 42000, salary_max: 65000, salary_currency: 'GBP', visa_type: 'Skilled Worker', experience_min: 3, qualification: 'bachelors', skills: ['CAD/CAM', 'FEA', 'Thermodynamics', 'GD&T', 'MATLAB'] },
      { company: 'BT Group', title: 'DevOps Engineer', description: 'Build and maintain CI/CD pipelines and cloud infrastructure for BT\'s next-generation network services. You will ensure 99.99% uptime for services used by millions of UK customers.', country: 'United Kingdom', city: 'London', industry: 'Telecom', salary_min: 50000, salary_max: 75000, salary_currency: 'GBP', visa_type: 'Skilled Worker', experience_min: 3, qualification: 'bachelors', skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'Jenkins'] },

      // ── USA Jobs ────────────────────────────────────────────────────────────
      { company: 'Google', title: 'Senior Software Engineer', description: 'Build planet-scale infrastructure that powers Google\'s core products. You will lead technical design reviews and mentor junior engineers on a team of world-class developers.', country: 'United States', city: 'Mountain View', industry: 'Technology', salary_min: 180000, salary_max: 300000, salary_currency: 'USD', visa_type: 'H-1B', experience_min: 5, qualification: 'masters', skills: ['C++', 'Python', 'System Design', 'Machine Learning'] },
      { company: 'Meta', title: 'Data Scientist', description: 'Use advanced statistical methods and machine learning to derive insights from Meta\'s massive user datasets. Your work directly influences product strategy and user experience for billions of people.', country: 'United States', city: 'Menlo Park', industry: 'Technology', salary_min: 160000, salary_max: 250000, salary_currency: 'USD', visa_type: 'H-1B', experience_min: 3, qualification: 'masters', skills: ['Python', 'SQL', 'Machine Learning', 'Statistics', 'A/B Testing'] },
      { company: 'Amazon', title: 'Product Manager', description: 'Own the product roadmap for a key Amazon Web Services offering. You will define the vision, prioritise features, and work with engineering teams to deliver world-class cloud products.', country: 'United States', city: 'Seattle', industry: 'Technology', salary_min: 150000, salary_max: 240000, salary_currency: 'USD', visa_type: 'H-1B', experience_min: 4, qualification: 'bachelors', skills: ['Product Strategy', 'Agile', 'Cloud Computing', 'Data Analysis'] },
      { company: 'Apple', title: 'UX Designer', description: 'Design intuitive user experiences for Apple\'s next-generation products. You will conduct user research, create prototypes, and collaborate closely with engineering to ship pixel-perfect interfaces.', country: 'United States', city: 'Cupertino', industry: 'Technology', salary_min: 140000, salary_max: 220000, salary_currency: 'USD', visa_type: 'H-1B', experience_min: 3, qualification: 'bachelors', skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Accessibility'] },
      { company: 'Tesla', title: 'Mechanical Engineer', description: 'Design and validate structural components for Tesla\'s next-generation electric vehicles. You will work in a fast-paced environment where innovation and first-principles thinking are essential.', country: 'United States', city: 'Austin', industry: 'Automotive', salary_min: 120000, salary_max: 180000, salary_currency: 'USD', visa_type: 'H-1B', experience_min: 3, qualification: 'masters', skills: ['SolidWorks', 'FEA', 'GD&T', 'Manufacturing Processes'] },
      { company: 'Goldman Sachs', title: 'Financial Analyst', description: 'Provide quantitative analysis and financial modelling for Goldman Sachs\' investment banking division. You will work on IPOs, M&A deals, and capital markets transactions.', country: 'United States', city: 'New York', industry: 'Finance', salary_min: 100000, salary_max: 160000, salary_currency: 'USD', visa_type: 'H-1B', experience_min: 2, qualification: 'bachelors', skills: ['Financial Modelling', 'Excel', 'Python', 'Bloomberg', 'Valuation'] },
      { company: 'McKinsey', title: 'Management Consultant', description: 'Solve complex business problems for Fortune 500 clients across industries. McKinsey sponsors visas for exceptional candidates and offers a globally mobile career path.', country: 'United States', city: 'New York', industry: 'Consulting', salary_min: 110000, salary_max: 190000, salary_currency: 'USD', visa_type: 'H-1B', experience_min: 2, qualification: 'masters', skills: ['Problem Solving', 'Data Analysis', 'Strategy', 'Communication'] },
      { company: 'Salesforce', title: 'Cloud Architect', description: 'Design and implement enterprise cloud solutions on the Salesforce platform for global customers. You will define architecture patterns and guide development teams on best practices.', country: 'United States', city: 'San Francisco', industry: 'Technology', salary_min: 170000, salary_max: 260000, salary_currency: 'USD', visa_type: 'H-1B', experience_min: 6, qualification: 'bachelors', skills: ['Salesforce', 'AWS', 'System Architecture', 'API Design', 'Microservices'] },
      { company: 'Stripe', title: 'Software Engineer', description: 'Build the financial infrastructure that powers internet commerce. Stripe engineers work on payment processing systems handling billions of dollars in transactions annually.', country: 'United States', city: 'San Francisco', industry: 'Finance', salary_min: 160000, salary_max: 250000, salary_currency: 'USD', visa_type: 'H-1B', experience_min: 3, qualification: 'bachelors', skills: ['Ruby', 'Go', 'Distributed Systems', 'Payments', 'API Design'] },
      { company: 'Netflix', title: 'Data Scientist', description: 'Build recommendation algorithms and A/B testing frameworks that shape what 230 million subscribers watch. You will work with petabyte-scale data to optimise the viewing experience.', country: 'United States', city: 'Los Gatos', industry: 'Technology', salary_min: 170000, salary_max: 280000, salary_currency: 'USD', visa_type: 'H-1B', experience_min: 4, qualification: 'masters', skills: ['Python', 'Spark', 'Deep Learning', 'Statistics', 'Experimentation'] },

      // ── Canada Jobs ─────────────────────────────────────────────────────────
      { company: 'Shopify', title: 'Software Engineer', description: 'Build and scale Shopify\'s commerce platform used by millions of merchants worldwide. You will work with Ruby on Rails and React in a fully remote-friendly engineering culture.', country: 'Canada', city: 'Toronto', industry: 'Technology', salary_min: 90000, salary_max: 150000, salary_currency: 'CAD', visa_type: 'LMIA', experience_min: 2, qualification: 'bachelors', skills: ['Ruby on Rails', 'React', 'GraphQL', 'MySQL'] },
      { company: 'RBC', title: 'Accountant', description: 'Manage financial reporting and regulatory compliance for one of Canada\'s largest banks. You will prepare consolidated financial statements and support audit processes.', country: 'Canada', city: 'Toronto', industry: 'Finance', salary_min: 65000, salary_max: 95000, salary_currency: 'CAD', visa_type: 'LMIA', experience_min: 2, qualification: 'bachelors', skills: ['IFRS', 'CPA', 'Financial Reporting', 'SAP'] },
      { company: 'Google Canada', title: 'Product Manager', description: 'Lead product development for Google\'s AI and machine learning initiatives from the Waterloo office. You will define product requirements and work with world-class engineering talent.', country: 'Canada', city: 'Waterloo', industry: 'Technology', salary_min: 120000, salary_max: 180000, salary_currency: 'CAD', visa_type: 'Global Talent', experience_min: 4, qualification: 'masters', skills: ['Product Management', 'AI/ML', 'Agile', 'Data Analysis'] },
      { company: 'Bombardier', title: 'Civil Engineer', description: 'Work on structural design and analysis for Bombardier\'s aerospace manufacturing facilities. You will ensure compliance with building codes and oversee construction projects.', country: 'Canada', city: 'Montreal', industry: 'Aerospace', salary_min: 75000, salary_max: 110000, salary_currency: 'CAD', visa_type: 'LMIA', experience_min: 3, qualification: 'bachelors', skills: ['AutoCAD', 'Structural Analysis', 'Project Management', 'Building Codes'] },
      { company: 'Bell', title: 'Marketing Manager', description: 'Lead marketing campaigns for Bell\'s consumer wireless and internet products. You will develop go-to-market strategies and manage a team of marketing specialists.', country: 'Canada', city: 'Montreal', industry: 'Telecom', salary_min: 80000, salary_max: 120000, salary_currency: 'CAD', visa_type: 'LMIA', experience_min: 5, qualification: 'bachelors', skills: ['Digital Marketing', 'Brand Strategy', 'Campaign Management', 'Analytics'] },

      // ── Germany Jobs ────────────────────────────────────────────────────────
      { company: 'SAP', title: 'Software Engineer', description: 'Develop enterprise software solutions at SAP\'s headquarters in Walldorf. You will work on cloud-native applications using cutting-edge technologies in a diverse international team.', country: 'Germany', city: 'Walldorf', industry: 'Technology', salary_min: 55000, salary_max: 85000, salary_currency: 'EUR', visa_type: 'EU Blue Card', experience_min: 2, qualification: 'bachelors', skills: ['Java', 'JavaScript', 'Cloud Foundry', 'HANA', 'Microservices'] },
      { company: 'BMW', title: 'Mechanical Engineer', description: 'Design and test components for BMW\'s next-generation electric vehicles. You will work at the forefront of automotive innovation in Munich\'s world-class engineering facilities.', country: 'Germany', city: 'Munich', industry: 'Automotive', salary_min: 55000, salary_max: 80000, salary_currency: 'EUR', visa_type: 'EU Blue Card', experience_min: 3, qualification: 'masters', skills: ['CATIA', 'FEA', 'Automotive Engineering', 'German B1'] },
      { company: 'Deutsche Bank', title: 'Financial Analyst', description: 'Provide quantitative analysis for Deutsche Bank\'s capital markets division in Frankfurt. You will model risk scenarios and support trading desk decisions using advanced analytics.', country: 'Germany', city: 'Frankfurt', industry: 'Finance', salary_min: 50000, salary_max: 75000, salary_currency: 'EUR', visa_type: 'EU Blue Card', experience_min: 2, qualification: 'masters', skills: ['Python', 'Financial Modelling', 'Risk Analysis', 'Bloomberg'] },
      { company: 'Siemens', title: 'DevOps Engineer', description: 'Automate and manage cloud infrastructure for Siemens\' digital industries division. You will build CI/CD pipelines and ensure high availability of industrial IoT platforms.', country: 'Germany', city: 'Munich', industry: 'Technology', salary_min: 55000, salary_max: 80000, salary_currency: 'EUR', visa_type: 'EU Blue Card', experience_min: 3, qualification: 'bachelors', skills: ['Azure', 'Docker', 'Kubernetes', 'Terraform', 'Python'] },
      { company: 'Bayer', title: 'Pharmacist', description: 'Join Bayer\'s pharmaceutical division as a regulatory affairs pharmacist. You will support drug registration processes and ensure compliance with EMA and global regulatory standards.', country: 'Germany', city: 'Leverkusen', industry: 'Healthcare', salary_min: 50000, salary_max: 72000, salary_currency: 'EUR', visa_type: 'EU Blue Card', experience_min: 2, qualification: 'masters', skills: ['Regulatory Affairs', 'GMP', 'Pharmacovigilance', 'EU Regulations'] },

      // ── Australia Jobs ──────────────────────────────────────────────────────
      { company: 'Atlassian', title: 'Software Engineer', description: 'Build collaboration tools used by millions of teams worldwide at Atlassian\'s Sydney headquarters. You will work on products like Jira and Confluence in an innovative engineering culture.', country: 'Australia', city: 'Sydney', industry: 'Technology', salary_min: 110000, salary_max: 170000, salary_currency: 'AUD', visa_type: '482 Visa', experience_min: 2, qualification: 'bachelors', skills: ['Java', 'React', 'AWS', 'Microservices'] },
      { company: 'BHP', title: 'Operations Manager', description: 'Manage mining operations at one of BHP\'s flagship iron ore sites in Western Australia. You will oversee safety, production targets, and a team of 200+ operational staff.', country: 'Australia', city: 'Perth', industry: 'Mining', salary_min: 150000, salary_max: 220000, salary_currency: 'AUD', visa_type: '482 Visa', experience_min: 8, qualification: 'bachelors', skills: ['Operations Management', 'Safety Management', 'Mining', 'Leadership'] },
      { company: 'Commonwealth Bank', title: 'Data Scientist', description: 'Apply machine learning to detect fraud and personalise banking experiences for 16 million CommBank customers. You will work with Australia\'s largest financial dataset.', country: 'Australia', city: 'Sydney', industry: 'Finance', salary_min: 110000, salary_max: 160000, salary_currency: 'AUD', visa_type: '482 Visa', experience_min: 3, qualification: 'masters', skills: ['Python', 'SQL', 'Machine Learning', 'TensorFlow', 'Statistics'] },
      { company: 'Canva', title: 'Product Manager', description: 'Shape the future of visual communication by leading product development at Canva. You will drive strategy for features used by 150 million monthly active users worldwide.', country: 'Australia', city: 'Sydney', industry: 'Technology', salary_min: 130000, salary_max: 185000, salary_currency: 'AUD', visa_type: '482 Visa', experience_min: 4, qualification: 'bachelors', skills: ['Product Strategy', 'Agile', 'User Research', 'Data Analysis'] },
      { company: 'Telstra', title: 'Cloud Architect', description: 'Design cloud-native solutions for Telstra\'s 5G and enterprise networking platforms. You will lead architecture decisions for Australia\'s largest telecommunications provider.', country: 'Australia', city: 'Melbourne', industry: 'Telecom', salary_min: 140000, salary_max: 200000, salary_currency: 'AUD', visa_type: '482 Visa', experience_min: 6, qualification: 'bachelors', skills: ['AWS', 'Azure', 'Network Architecture', '5G', 'Microservices'] },

      // ── UAE Jobs ────────────────────────────────────────────────────────────
      { company: 'Emirates', title: 'HR Manager', description: 'Lead human resources operations for Emirates\' cabin crew division of 20,000+ employees. You will manage recruitment, training programmes, and employee engagement initiatives.', country: 'United Arab Emirates', city: 'Dubai', industry: 'Aerospace', salary_min: 25000, salary_max: 40000, salary_currency: 'AED', visa_type: 'Employment Visa', experience_min: 5, qualification: 'bachelors', skills: ['HR Management', 'Recruitment', 'Employee Relations', 'HRIS'] },
      { company: 'ADNOC', title: 'Mechanical Engineer', description: 'Design and maintain critical oil and gas processing equipment at ADNOC\'s onshore facilities. You will ensure operational safety and optimise plant performance in Abu Dhabi.', country: 'United Arab Emirates', city: 'Abu Dhabi', industry: 'Energy', salary_min: 20000, salary_max: 35000, salary_currency: 'AED', visa_type: 'Employment Visa', experience_min: 4, qualification: 'bachelors', skills: ['Process Engineering', 'P&ID', 'ASME', 'AutoCAD', 'Oil & Gas'] },
      { company: 'Emaar', title: 'Project Manager', description: 'Manage large-scale construction projects for Emaar, the developer behind the Burj Khalifa. You will coordinate with contractors, architects, and stakeholders on iconic Dubai developments.', country: 'United Arab Emirates', city: 'Dubai', industry: 'Finance', salary_min: 25000, salary_max: 45000, salary_currency: 'AED', visa_type: 'Employment Visa', experience_min: 6, qualification: 'bachelors', skills: ['Project Management', 'PMP', 'Construction', 'Stakeholder Management', 'MS Project'] },
      { company: 'Majid Al Futtaim', title: 'Sales Director', description: 'Lead the retail sales strategy for Majid Al Futtaim\'s portfolio of shopping malls and retail brands across the Middle East and North Africa region.', country: 'United Arab Emirates', city: 'Dubai', industry: 'Retail', salary_min: 35000, salary_max: 55000, salary_currency: 'AED', visa_type: 'Employment Visa', experience_min: 8, qualification: 'bachelors', skills: ['Sales Strategy', 'Retail Management', 'P&L Management', 'Team Leadership'] },
      { company: 'Dubai Holding', title: 'Accountant', description: 'Manage financial accounting and reporting for Dubai Holding\'s diversified investment portfolio. You will prepare consolidated financial statements and support strategic financial planning.', country: 'United Arab Emirates', city: 'Dubai', industry: 'Finance', salary_min: 15000, salary_max: 25000, salary_currency: 'AED', visa_type: 'Employment Visa', experience_min: 3, qualification: 'bachelors', skills: ['IFRS', 'SAP', 'Financial Reporting', 'ACCA'] },

      // ── Extra cross-country roles ──────────────────────────────────────────
      { company: 'Microsoft', title: 'Cloud Architect', description: 'Design and implement Azure cloud solutions for enterprise clients. You will serve as a technical authority on hybrid cloud strategies and lead proof-of-concept deployments.', country: 'United States', city: 'Redmond', industry: 'Technology', salary_min: 170000, salary_max: 270000, salary_currency: 'USD', visa_type: 'H-1B', experience_min: 7, qualification: 'masters', skills: ['Azure', 'System Architecture', 'Networking', 'Security', 'DevOps'] },
      { company: 'PwC UK', title: 'Accountant', description: 'Provide audit and assurance services to FTSE 100 clients at PwC\'s London office. You will gain exposure to complex financial reporting and multi-jurisdictional engagements.', country: 'United Kingdom', city: 'London', industry: 'Consulting', salary_min: 32000, salary_max: 50000, salary_currency: 'GBP', visa_type: 'Skilled Worker', experience_min: 1, qualification: 'bachelors', skills: ['IFRS', 'ACA/ACCA', 'Audit', 'Financial Analysis'] },
      { company: 'Microsoft Canada', title: 'Software Engineer', description: 'Join Microsoft\'s Vancouver development centre working on Azure cloud infrastructure. You will build highly available distributed systems serving millions of enterprise customers.', country: 'Canada', city: 'Vancouver', industry: 'Technology', salary_min: 100000, salary_max: 160000, salary_currency: 'CAD', visa_type: 'Global Talent', experience_min: 3, qualification: 'bachelors', skills: ['C#', '.NET', 'Azure', 'Distributed Systems'] },
      { company: 'GSK', title: 'Data Scientist', description: 'Apply AI and machine learning to accelerate drug discovery at GSK\'s R&D centre. You will work with genomic data and clinical trial datasets to identify promising therapeutic targets.', country: 'United Kingdom', city: 'Stevenage', industry: 'Healthcare', salary_min: 50000, salary_max: 80000, salary_currency: 'GBP', visa_type: 'Skilled Worker', experience_min: 3, qualification: 'phd', skills: ['Python', 'R', 'Machine Learning', 'Bioinformatics', 'Statistics'] },
      { company: 'Scotiabank', title: 'Financial Analyst', description: 'Conduct financial analysis and risk assessment for Scotiabank\'s global banking and markets division. You will support credit decisions and portfolio management for institutional clients.', country: 'Canada', city: 'Toronto', industry: 'Finance', salary_min: 70000, salary_max: 100000, salary_currency: 'CAD', visa_type: 'LMIA', experience_min: 2, qualification: 'bachelors', skills: ['Financial Analysis', 'Risk Management', 'Excel', 'Bloomberg'] },
    ];

    let jobCount = 0;
    for (const j of jobsData) {
      const cid = companyIds[j.company];
      if (!cid) {
        console.warn(`  ⚠ Skipping job "${j.title}" — company "${j.company}" not found`);
        continue;
      }
      await query(`
        INSERT INTO jobs (company_id, title, description, country, city, industry,
                          salary_min, salary_max, salary_currency, visa_sponsored, visa_type,
                          experience_min, qualification, skills, employment_type, status)
        VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,TRUE,$10,$11,$12,$13::jsonb,'full-time','active')
        ON CONFLICT DO NOTHING
      `, [cid, j.title, j.description, j.country, j.city, j.industry,
          j.salary_min, j.salary_max, j.salary_currency, j.visa_type,
          j.experience_min, j.qualification, JSON.stringify(j.skills)]);
      jobCount++;
    }

    console.log(`  ✓ ${jobCount} jobs seeded`);

    // ═══════════════════════════════════════════════════════════════════════════
    //  NEWS
    // ═══════════════════════════════════════════════════════════════════════════

    const newsData = [
      { title: 'UK Increases Skilled Worker Visa Salary Threshold to £38,700', summary: 'The UK Home Office has raised the minimum salary for Skilled Worker visa sponsorship from £26,200 to £38,700. The change affects new applications from April 2024 and is expected to reduce net migration significantly.', category: 'visa_update', country: 'United Kingdom', is_featured: true, source: 'BBC', image_url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=600&h=400&fit=crop' },
      { title: 'Canada Opens New Pathway for African Tech Workers', summary: 'Immigration, Refugees and Citizenship Canada (IRCC) announced a dedicated tech talent stream targeting skilled workers from African nations. The programme offers expedited processing and LMIA exemptions for qualifying applicants.', category: 'immigration', country: 'Canada', is_featured: true, source: 'Reuters', image_url: 'https://images.unsplash.com/photo-1517935706615-2717063c2225?w=600&h=400&fit=crop' },
      { title: 'Chevening Scholarships 2025/2026 Now Open for Applications', summary: 'The UK government\'s prestigious Chevening Scholarship programme is accepting applications for the 2025/2026 academic year. The fully-funded scholarship covers tuition, living expenses, and flights for a one-year master\'s degree at any UK university.', category: 'scholarship', country: 'United Kingdom', is_featured: true, source: 'The Guardian', image_url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&h=400&fit=crop' },
      { title: 'Australia Introduces New Skills in Demand Visa', summary: 'The Australian government has launched the new Skills in Demand visa to replace the Temporary Skill Shortage (subclass 482) visa. The new visa offers a streamlined pathway to permanent residency for workers in critical occupations.', category: 'visa_update', country: 'Australia', is_featured: false, source: 'ABC News', image_url: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=600&h=400&fit=crop' },
      { title: 'UAE Golden Visa Extended to Remote Workers and Freelancers', summary: 'The UAE has expanded its Golden Visa programme to include remote workers and freelancers earning above AED 50,000 monthly. The 10-year renewable visa offers full residency benefits without requiring a local employer sponsor.', category: 'visa_update', country: 'United Arab Emirates', is_featured: false, source: 'Gulf News', image_url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&h=400&fit=crop' },
      { title: 'Germany Simplifies EU Blue Card Requirements for Tech Workers', summary: 'Germany has lowered the salary threshold for EU Blue Card applicants in IT and STEM fields to €41,042 annually. The reform also removes the requirement for formal degree recognition for experienced professionals.', category: 'visa_update', country: 'Germany', is_featured: false, source: 'DW News', image_url: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=600&h=400&fit=crop' },
      { title: 'Nigeria-UK Direct Flights Resume After 5 Years', summary: 'British Airways has resumed direct flights between Lagos and London Heathrow after a five-year suspension. The restored route operates four times weekly and is expected to boost business travel and tourism between the two countries.', category: 'travel_advisory', country: 'United Kingdom', is_featured: false, source: 'BBC', image_url: 'https://images.unsplash.com/photo-1436491865332-7a61a109db05?w=600&h=400&fit=crop' },
      { title: 'South Africa Added to UK Electronic Travel Authorisation Requirements', summary: 'South African nationals will now need an Electronic Travel Authorisation (ETA) to enter the United Kingdom from January 2025. The ETA costs £10 and must be obtained before travel.', category: 'travel_advisory', country: 'United Kingdom', is_featured: false, source: 'The Guardian', image_url: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=600&h=400&fit=crop' },
      { title: 'Canadian Express Entry Draw Sets Record Low CRS Score of 481', summary: 'IRCC\'s latest Express Entry draw invited 5,500 candidates with a minimum Comprehensive Ranking System score of 481. The declining cut-off scores signal increased opportunities for skilled workers planning to immigrate to Canada.', category: 'immigration', country: 'Canada', is_featured: false, source: 'CIC News', image_url: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=600&h=400&fit=crop' },
      { title: 'UK Graduate Route Visa Under Review Amid Migration Debate', summary: 'The UK government has commissioned an independent review of the Graduate Route visa, which allows international students to stay and work for two years after completing their degree. The review may lead to restrictions on eligible courses and institutions.', category: 'visa_update', country: 'United Kingdom', is_featured: false, source: 'Financial Times', image_url: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=600&h=400&fit=crop' },
      { title: 'Tech Giants Increase H-1B Visa Sponsorship Despite Layoffs', summary: 'Despite high-profile layoffs across the tech sector, companies like Google, Microsoft, and Amazon have increased their H-1B visa petition filings by 12% year-over-year. Demand for specialised AI and cloud computing talent continues to drive visa sponsorship.', category: 'jobs', country: 'United States', is_featured: false, source: 'Bloomberg', image_url: 'https://images.unsplash.com/photo-1504384764586-bb4cdc1707b0?w=600&h=400&fit=crop' },
      { title: 'From Lagos to London: How Adaeze Built a Career in NHS Nursing', summary: 'Adaeze Nwosu shares her journey from nursing in Nigeria to becoming a ward sister at a London NHS hospital. Her story highlights the support available for international healthcare workers including visa sponsorship and OSCE preparation.', category: 'success_story', country: 'United Kingdom', is_featured: false, source: 'Tragency', image_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=400&fit=crop' },
      { title: 'Australia Adds Healthcare and Engineering to Priority Migration Skilled Occupation List', summary: 'The Australian Department of Home Affairs has added 15 new occupations to the Priority Migration Skilled Occupation List including registered nurses, civil engineers, and pharmacists. Workers in these roles benefit from faster visa processing.', category: 'immigration', country: 'Australia', is_featured: false, source: 'SBS News', image_url: 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=600&h=400&fit=crop' },
      { title: 'Commonwealth Shared Scholarships 2025 Open for Developing Countries', summary: 'The Commonwealth Scholarship Commission has opened applications for the 2025 Shared Scholarships aimed at students from developing Commonwealth nations. The scholarships fund full master\'s degree programmes at participating UK universities.', category: 'scholarship', country: 'United Kingdom', is_featured: false, source: 'The Guardian', image_url: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&h=400&fit=crop' },
      { title: 'Germany Launches Opportunity Card for Job Seekers Without an Offer', summary: 'Germany\'s new Chancenkarte (Opportunity Card) allows skilled workers to enter Germany for up to one year to search for employment without a prior job offer. Applicants need to score enough points based on qualifications, language skills, and age.', category: 'visa_update', country: 'Germany', is_featured: false, source: 'DW News', image_url: 'https://images.unsplash.com/photo-1449452198679-05c7fd30f416?w=600&h=400&fit=crop' },
      { title: 'UAE and India Sign Mutual Visa Facilitation Agreement', summary: 'The UAE and India have signed a new agreement to simplify visa procedures for business travellers and tourists. The agreement introduces a 60-day visa on arrival for Indian nationals and streamlined work permit transfers.', category: 'visa_update', country: 'United Arab Emirates', is_featured: false, source: 'Gulf News', image_url: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=600&h=400&fit=crop' },
      { title: 'Software Engineer Relocates from Nairobi to Toronto via Global Talent Stream', summary: 'Brian Kamau shares how he leveraged Canada\'s Global Talent Stream to relocate from Kenya to Toronto and join Shopify as a senior engineer. The process took just eight weeks from application to landing.', category: 'success_story', country: 'Canada', is_featured: false, source: 'Tragency', image_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&h=400&fit=crop' },
      { title: 'IELTS Requirement Waived for Nurses from English-Speaking Countries', summary: 'The UK Nursing and Midwifery Council has waived the IELTS requirement for nurses who trained in majority English-speaking countries including Nigeria, Ghana, and Kenya. This is expected to accelerate the recruitment of international nurses to the NHS.', category: 'visa_update', country: 'United Kingdom', is_featured: false, source: 'Nursing Times', image_url: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&h=400&fit=crop' },
    ];

    let newsCount = 0;
    for (const n of newsData) {
      await query(`
        INSERT INTO news (title, summary, source, image_url, category, country, is_featured)
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        ON CONFLICT DO NOTHING
      `, [n.title, n.summary, n.source, n.image_url, n.category, n.country || null, n.is_featured]);
      newsCount++;
    }

    console.log(`  ✓ ${newsCount} news articles seeded`);

    console.log('\n✅ V3 seeding complete!\n');
  } catch (err) {
    console.error('❌ V3 Seed failed:', err.message);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

seed();
