require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
if (!process.env.DB_HOST && !process.env.DATABASE_URL) require('dotenv').config();
const { query } = require('./db');

async function seedV10() {
  console.log('Seeding V10 data (scholarships + cost of living)...');

  // ── Scholarships ──────────────────────────────────────────────────────────

  const scholarships = [
    // Canada
    { name: 'Vanier Canada Graduate Scholarships', country: 'Canada', university: 'Various Canadian Universities', degree_level: 'PhD', field_of_study: 'All Fields', amount: '50000', currency: 'USD', coverage: 'Full tuition, living expenses, health insurance for 3 years', deadline: 'November 1, 2026', eligibility: 'International students pursuing PhD at a Canadian institution', apply_url: 'https://vanier.gc.ca', description: 'Canada\'s most prestigious graduate scholarship, awarded to world-class doctoral students.', is_full_ride: true },
    { name: 'Lester B. Pearson International Scholarships', country: 'Canada', university: 'University of Toronto', degree_level: 'Bachelors', field_of_study: 'All Fields', amount: '65000', currency: 'USD', coverage: 'Full tuition, books, incidental fees, residence for 4 years', deadline: 'January 15, 2027', eligibility: 'International students nominated by their school', apply_url: 'https://future.utoronto.ca/pearson', description: 'Recognizes students who demonstrate exceptional academic achievement and creativity.', is_full_ride: true },
    { name: 'University of British Columbia International Leader of Tomorrow', country: 'Canada', university: 'University of British Columbia', degree_level: 'Bachelors', field_of_study: 'All Fields', amount: '40000', currency: 'USD', coverage: 'Partial to full tuition coverage renewable for 4 years', deadline: 'December 1, 2026', eligibility: 'International students with demonstrated leadership and academic excellence', apply_url: 'https://you.ubc.ca/financial-planning/scholarships-awards', description: 'Awards for international students who demonstrate leadership and involvement in community.', is_full_ride: false },
    { name: 'McGill Entrance Scholarships', country: 'Canada', university: 'McGill University', degree_level: 'Bachelors', field_of_study: 'All Fields', amount: '12000', currency: 'USD', coverage: 'Renewable annual award for up to 4 years', deadline: 'January 15, 2027', eligibility: 'International students with outstanding academic records', apply_url: 'https://mcgill.ca/studentaid/scholarships', description: 'Competitive entrance scholarships for high-achieving incoming students.', is_full_ride: false },
    { name: 'University of Calgary International Entrance Scholarship', country: 'Canada', university: 'University of Calgary', degree_level: 'Bachelors', field_of_study: 'All Fields', amount: '15000', currency: 'USD', coverage: 'One-time entrance award', deadline: 'December 1, 2026', eligibility: 'International students with minimum 90% average', apply_url: 'https://ucalgary.ca/registrar/awards', description: 'Merit-based award for exceptional international students entering undergraduate programs.', is_full_ride: false },
    { name: 'Ontario Trillium Scholarship', country: 'Canada', university: 'Various Ontario Universities', degree_level: 'PhD', field_of_study: 'All Fields', amount: '40000', currency: 'USD', coverage: 'Annual stipend renewable for up to 4 years', deadline: 'Varies by university', eligibility: 'International PhD students at Ontario universities', apply_url: 'https://ontario.ca/page/ontario-trillium-scholarship', description: 'Attracts top international doctoral students to Ontario universities.', is_full_ride: true },
    { name: 'University of Waterloo International Master\'s Award of Excellence', country: 'Canada', university: 'University of Waterloo', degree_level: 'Masters', field_of_study: 'Engineering, Science, Mathematics', amount: '12500', currency: 'USD', coverage: 'One-time award for first year of study', deadline: 'February 1, 2027', eligibility: 'International master\'s applicants with 80%+ average', apply_url: 'https://uwaterloo.ca/graduate-studies-postdoctoral-affairs/awards', description: 'Competitive award for outstanding international master\'s students in STEM.', is_full_ride: false },

    // UK
    { name: 'Chevening Scholarships', country: 'UK', university: 'Various UK Universities', degree_level: 'Masters', field_of_study: 'All Fields', amount: '45000', currency: 'USD', coverage: 'Full tuition, living expenses, flights, visa, thesis grant', deadline: 'November 7, 2026', eligibility: 'International students with 2+ years work experience and leadership potential', apply_url: 'https://chevening.org/scholarships', description: 'The UK government\'s global scholarship programme, funded by the FCDO.', is_full_ride: true },
    { name: 'Gates Cambridge Scholarship', country: 'UK', university: 'University of Cambridge', degree_level: 'PhD', field_of_study: 'All Fields', amount: '55000', currency: 'USD', coverage: 'Full cost of study, maintenance allowance, airfare, visa costs', deadline: 'October 12, 2026', eligibility: 'Outstanding international applicants from outside the UK', apply_url: 'https://gatescambridge.org', description: 'One of the most prestigious scholarships in the world for postgraduate study at Cambridge.', is_full_ride: true },
    { name: 'Rhodes Scholarship', country: 'UK', university: 'University of Oxford', degree_level: 'Masters', field_of_study: 'All Fields', amount: '70000', currency: 'USD', coverage: 'Full tuition, personal stipend, flights, health insurance', deadline: 'October 1, 2026', eligibility: 'Outstanding young people from select countries, ages 19-25', apply_url: 'https://rhodeshouse.ox.ac.uk', description: 'The oldest and most celebrated international scholarship, established in 1903.', is_full_ride: true },
    { name: 'Commonwealth Shared Scholarships', country: 'UK', university: 'Various UK Universities', degree_level: 'Masters', field_of_study: 'Development-related fields', amount: '38000', currency: 'USD', coverage: 'Full tuition, living costs, return airfare', deadline: 'December 19, 2026', eligibility: 'Students from eligible Commonwealth developing countries', apply_url: 'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-shared-scholarships', description: 'For students from developing Commonwealth countries who could not otherwise study in the UK.', is_full_ride: true },
    { name: 'Clarendon Scholarship', country: 'UK', university: 'University of Oxford', degree_level: 'Masters', field_of_study: 'All Fields', amount: '50000', currency: 'USD', coverage: 'Full tuition and generous living allowance', deadline: 'January 6, 2027', eligibility: 'All graduate applicants to Oxford — automatic consideration', apply_url: 'https://clarendon.ox.ac.uk', description: 'Oxford\'s largest and most prestigious scholarship programme with 140+ awards annually.', is_full_ride: true },
    { name: 'Edinburgh Global Research Scholarship', country: 'UK', university: 'University of Edinburgh', degree_level: 'PhD', field_of_study: 'All Fields', amount: '15000', currency: 'USD', coverage: 'Covers difference between home and international tuition', deadline: 'February 1, 2027', eligibility: 'International PhD applicants to the University of Edinburgh', apply_url: 'https://ed.ac.uk/student-funding/postgraduate/international', description: 'Competitive award bridging the gap between home and overseas fees for doctoral students.', is_full_ride: false },
    { name: 'Imperial College London President\'s PhD Scholarships', country: 'UK', university: 'Imperial College London', degree_level: 'PhD', field_of_study: 'Science, Engineering, Medicine', amount: '52000', currency: 'USD', coverage: 'Full tuition waiver plus enhanced stipend for 3.5 years', deadline: 'January 14, 2027', eligibility: 'Exceptional international PhD candidates in STEM', apply_url: 'https://imperial.ac.uk/study/fees-and-funding/postgraduate-doctoral/grants-scholarships/presidents-phd', description: 'Imperial\'s flagship doctoral funding for the most exceptional research students.', is_full_ride: true },

    // US
    { name: 'Fulbright Foreign Student Program', country: 'US', university: 'Various US Universities', degree_level: 'Masters', field_of_study: 'All Fields', amount: '50000', currency: 'USD', coverage: 'Full tuition, living stipend, airfare, health insurance', deadline: 'Varies by country (Feb-Oct)', eligibility: 'International students from 160+ countries with bachelor\'s degree', apply_url: 'https://foreign.fulbrightonline.org', description: 'The flagship international exchange programme sponsored by the US government.', is_full_ride: true },
    { name: 'Stanford Knight-Hennessy Scholars', country: 'US', university: 'Stanford University', degree_level: 'Masters', field_of_study: 'All Fields', amount: '90000', currency: 'USD', coverage: 'Full tuition, stipend, travel, and enrichment funding for up to 3 years', deadline: 'October 12, 2026', eligibility: 'International students with bachelor\'s within last 7 years', apply_url: 'https://knight-hennessy.stanford.edu', description: 'The largest fully endowed scholars programme in the world, cultivating a community of future global leaders.', is_full_ride: true },
    { name: 'Yale University International Need-Based Aid', country: 'US', university: 'Yale University', degree_level: 'Bachelors', field_of_study: 'All Fields', amount: '75000', currency: 'USD', coverage: 'Full demonstrated need — tuition, room, board, travel', deadline: 'January 2, 2027', eligibility: 'All admitted international students with financial need', apply_url: 'https://finaid.yale.edu', description: 'Yale meets 100% of demonstrated financial need for all admitted students, including internationals.', is_full_ride: true },
    { name: 'MIT Undergraduate International Aid', country: 'US', university: 'Massachusetts Institute of Technology', degree_level: 'Bachelors', field_of_study: 'Science, Engineering, Technology', amount: '72000', currency: 'USD', coverage: 'Full need-based aid — tuition, housing, meals, books', deadline: 'January 5, 2027', eligibility: 'Admitted international students demonstrating financial need', apply_url: 'https://sfs.mit.edu', description: 'MIT provides full need-based financial aid to all admitted students regardless of nationality.', is_full_ride: true },
    { name: 'Mastercard Foundation Scholars Program', country: 'US', university: 'Various (Arizona State, Duke, Michigan)', degree_level: 'Bachelors', field_of_study: 'All Fields', amount: '60000', currency: 'USD', coverage: 'Full tuition, accommodation, books, stipend, mentorship', deadline: 'Varies by university', eligibility: 'Young Africans who are academically talented with financial need', apply_url: 'https://mastercardfdn.org/all/scholars', description: 'Enabling academically talented yet economically disadvantaged young people from Africa to complete quality education.', is_full_ride: true },
    { name: 'University of Michigan Rackham International Student Fellowship', country: 'US', university: 'University of Michigan', degree_level: 'PhD', field_of_study: 'All Fields', amount: '35000', currency: 'USD', coverage: 'Stipend plus tuition waiver for first year', deadline: 'January 15, 2027', eligibility: 'Outstanding international PhD applicants', apply_url: 'https://rackham.umich.edu/funding', description: 'Fellowship supporting exceptional international students in doctoral programmes.', is_full_ride: false },
    { name: 'Columbia University Obama Foundation Scholars', country: 'US', university: 'Columbia University', degree_level: 'Masters', field_of_study: 'Public Policy, International Affairs', amount: '80000', currency: 'USD', coverage: 'Full tuition, housing, stipend, leadership development', deadline: 'February 12, 2027', eligibility: 'Emerging leaders from Africa, Asia-Pacific, and Europe with civic engagement experience', apply_url: 'https://obama.org/scholars', description: 'A one-year programme at Columbia for emerging leaders committed to driving change.', is_full_ride: true },

    // Germany
    { name: 'DAAD Scholarships', country: 'Germany', university: 'Various German Universities', degree_level: 'Masters', field_of_study: 'All Fields', amount: '15500', currency: 'USD', coverage: 'Monthly stipend, travel allowance, health insurance, tuition waiver', deadline: 'October 15, 2026', eligibility: 'International graduates with bachelor\'s degree and 2+ years experience', apply_url: 'https://daad.de/en/study-and-research-in-germany/scholarships', description: 'Germany\'s largest funding organisation for international academic exchange.', is_full_ride: true },
    { name: 'Deutschlandstipendium', country: 'Germany', university: 'Various German Universities', degree_level: 'Bachelors', field_of_study: 'All Fields', amount: '3600', currency: 'USD', coverage: 'Monthly stipend of 300 EUR for one year, renewable', deadline: 'Varies by university', eligibility: 'International and domestic students based on merit and social engagement', apply_url: 'https://deutschlandstipendium.de/en', description: 'National scholarship programme combining public and private funding for talented students.', is_full_ride: false },
    { name: 'Heinrich Boll Foundation Scholarships', country: 'Germany', university: 'Various German Universities', degree_level: 'Masters', field_of_study: 'Social Sciences, Environment, Politics', amount: '12000', currency: 'USD', coverage: 'Monthly stipend plus health insurance and family allowances', deadline: 'September 1, 2026', eligibility: 'International students aligned with green political values and civic engagement', apply_url: 'https://boell.de/en/scholarships', description: 'Scholarships for students committed to ecology, democracy, and social justice.', is_full_ride: false },
    { name: 'Konrad-Adenauer-Stiftung Scholarship', country: 'Germany', university: 'Various German Universities', degree_level: 'Masters', field_of_study: 'All Fields', amount: '11000', currency: 'USD', coverage: 'Monthly stipend, study allowance, health insurance', deadline: 'July 15, 2026', eligibility: 'International students with above-average academic performance and social engagement', apply_url: 'https://kas.de/en/scholarships', description: 'Supporting future leaders from around the world with strong academic records.', is_full_ride: false },
    { name: 'TU Munich International Graduate School of Science and Engineering', country: 'Germany', university: 'Technical University of Munich', degree_level: 'PhD', field_of_study: 'Engineering, Natural Sciences', amount: '25000', currency: 'USD', coverage: 'Full salary as research associate, no tuition fees', deadline: 'Rolling admissions', eligibility: 'International master\'s graduates in engineering or natural sciences', apply_url: 'https://igsse.tum.de', description: 'Structured PhD programme at one of Europe\'s top technical universities.', is_full_ride: true },

    // Australia
    { name: 'Australia Awards Scholarships', country: 'Australia', university: 'Various Australian Universities', degree_level: 'Masters', field_of_study: 'All Fields', amount: '45000', currency: 'USD', coverage: 'Full tuition, return airfare, living allowance, health cover', deadline: 'April 30, 2027', eligibility: 'Citizens of eligible developing countries in Asia, Pacific, Africa', apply_url: 'https://australiaawards.gov.au', description: 'Long-term development awards funded by the Australian government for developing country nationals.', is_full_ride: true },
    { name: 'University of Melbourne Graduate Research Scholarships', country: 'Australia', university: 'University of Melbourne', degree_level: 'PhD', field_of_study: 'All Fields', amount: '35000', currency: 'USD', coverage: 'Full tuition offset, living allowance, relocation grant', deadline: 'October 31, 2026', eligibility: 'International students with first-class honours or equivalent', apply_url: 'https://scholarships.unimelb.edu.au', description: 'Competitive research scholarships for outstanding international doctoral candidates.', is_full_ride: true },
    { name: 'Monash International Leadership Scholarship', country: 'Australia', university: 'Monash University', degree_level: 'Bachelors', field_of_study: 'All Fields', amount: '50000', currency: 'USD', coverage: 'Full tuition fee waiver for entire course duration', deadline: 'November 30, 2026', eligibility: 'High-achieving international students with leadership qualities', apply_url: 'https://monash.edu/study/fees-scholarships/scholarships', description: 'Monash\'s premier undergraduate scholarship recognising academic excellence and leadership.', is_full_ride: true },
    { name: 'University of Sydney International Research Scholarship', country: 'Australia', university: 'University of Sydney', degree_level: 'PhD', field_of_study: 'All Fields', amount: '32000', currency: 'USD', coverage: 'Tuition fees and living allowance for up to 3.5 years', deadline: 'April 30, 2027', eligibility: 'International applicants for higher degree research programmes', apply_url: 'https://sydney.edu.au/scholarships/domestic/postgraduate-research.html', description: 'Supporting international researchers pursuing doctoral studies at a world top-50 university.', is_full_ride: true },
    { name: 'Destination Australia Scholarship', country: 'Australia', university: 'Various Regional Universities', degree_level: 'Bachelors', field_of_study: 'All Fields', amount: '15000', currency: 'USD', coverage: 'Annual stipend for study in regional Australia', deadline: 'Varies by institution', eligibility: 'International and domestic students studying at regional campuses', apply_url: 'https://education.gov.au/destination-australia', description: 'Government-funded scholarship encouraging students to study in regional Australia.', is_full_ride: false },

    // Netherlands
    { name: 'Holland Scholarship', country: 'Netherlands', university: 'Various Dutch Universities', degree_level: 'Bachelors', field_of_study: 'All Fields', amount: '5000', currency: 'USD', coverage: 'One-time award for first year of study', deadline: 'February 1, 2027', eligibility: 'Non-EEA international students applying to Dutch universities for first time', apply_url: 'https://studyinholland.nl/finances/holland-scholarship', description: 'Funded by the Dutch Ministry of Education to attract international talent.', is_full_ride: false },
    { name: 'Erasmus Mundus Joint Masters', country: 'Netherlands', university: 'Consortium of European Universities', degree_level: 'Masters', field_of_study: 'All Fields', amount: '49000', currency: 'USD', coverage: 'Full tuition, travel, installation costs, monthly allowance for 2 years', deadline: 'January 10, 2027', eligibility: 'International students applying to Erasmus Mundus joint programmes', apply_url: 'https://erasmus-plus.ec.europa.eu', description: 'EU-funded scholarships for top international master\'s programmes delivered by consortia of universities.', is_full_ride: true },
    { name: 'University of Amsterdam Excellence Scholarship', country: 'Netherlands', university: 'University of Amsterdam', degree_level: 'Masters', field_of_study: 'All Fields', amount: '25000', currency: 'USD', coverage: 'Full or partial tuition fee waiver plus living stipend', deadline: 'January 15, 2027', eligibility: 'Non-EU/EEA students with excellent academic records', apply_url: 'https://uva.nl/en/education/master-s/scholarships--tuition/scholarships-and-tuition.html', description: 'For exceptional international master\'s students at the University of Amsterdam.', is_full_ride: false },
    { name: 'Leiden University Excellence Scholarship (LExS)', country: 'Netherlands', university: 'Leiden University', degree_level: 'Masters', field_of_study: 'All Fields', amount: '15000', currency: 'USD', coverage: 'Tuition fee waiver of 10,000 or 15,000 EUR', deadline: 'February 1, 2027', eligibility: 'Non-EU/EEA students with outstanding study results', apply_url: 'https://universiteitleiden.nl/en/education/admission-and-application/masters/financial-matters/scholarships', description: 'Merit-based scholarship for talented international master\'s students.', is_full_ride: false },
    { name: 'TU Delft Excellence Scholarship', country: 'Netherlands', university: 'Delft University of Technology', degree_level: 'Masters', field_of_study: 'Engineering, Technology, Science', amount: '30000', currency: 'USD', coverage: 'Full tuition fee waiver plus monthly living allowance', deadline: 'December 1, 2026', eligibility: 'International MSc applicants with excellent academic record (top 10% of class)', apply_url: 'https://tudelft.nl/en/education/admission-and-application/msc/scholarships', description: 'Scholarships for outstanding international students in engineering and technology.', is_full_ride: true },

    // Japan
    { name: 'MEXT Japanese Government Scholarship', country: 'Japan', university: 'Various Japanese Universities', degree_level: 'Masters', field_of_study: 'All Fields', amount: '18000', currency: 'USD', coverage: 'Full tuition, monthly allowance, round-trip airfare', deadline: 'April 15, 2027', eligibility: 'International students from countries with diplomatic relations with Japan', apply_url: 'https://studyinjapan.go.jp/en/smap-stopj-applications-scholarship.html', description: 'Japanese government scholarship programme for international students at all levels.', is_full_ride: true },
    { name: 'JASSO Student Exchange Support Program', country: 'Japan', university: 'Various Japanese Universities', degree_level: 'Bachelors', field_of_study: 'All Fields', amount: '5800', currency: 'USD', coverage: 'Monthly stipend of 80,000 JPY', deadline: 'Varies by university', eligibility: 'International students enrolled in Japanese universities with good academic standing', apply_url: 'https://jasso.go.jp/en/ryugaku/scholarship', description: 'Support programme helping international students with living expenses during study in Japan.', is_full_ride: false },
    { name: 'University of Tokyo PEAK International Scholarship', country: 'Japan', university: 'University of Tokyo', degree_level: 'Bachelors', field_of_study: 'Science, Engineering, Liberal Arts', amount: '14000', currency: 'USD', coverage: 'Tuition exemption plus monthly living allowance', deadline: 'November 30, 2026', eligibility: 'International students applying to PEAK (Programs in English at Komaba)', apply_url: 'https://peak.c.u-tokyo.ac.jp', description: 'Full English-taught undergraduate programme at Japan\'s top university with financial support.', is_full_ride: true },
    { name: 'ADB-Japan Scholarship Program', country: 'Japan', university: 'Various Partner Universities', degree_level: 'Masters', field_of_study: 'Economics, Management, Science, Technology', amount: '22000', currency: 'USD', coverage: 'Full tuition, monthly stipend, housing, books, airfare, health insurance', deadline: 'Varies by university', eligibility: 'Nationals of ADB borrowing member countries with 2+ years professional experience', apply_url: 'https://adb.org/work-with-us/careers/japan-scholarship-program', description: 'Joint programme between Asian Development Bank and Japan for developing member country nationals.', is_full_ride: true },
    { name: 'Kyoto University International Graduate Scholarship', country: 'Japan', university: 'Kyoto University', degree_level: 'PhD', field_of_study: 'All Fields', amount: '16000', currency: 'USD', coverage: 'Monthly stipend plus tuition fee exemption', deadline: 'December 15, 2026', eligibility: 'International doctoral applicants with master\'s degree', apply_url: 'https://kyoto-u.ac.jp/en/education-campus/international-students', description: 'Financial support for international researchers pursuing doctoral studies at Kyoto University.', is_full_ride: true },

    // Additional mixed
    { name: 'Schwarzman Scholars', country: 'US', university: 'Tsinghua University (based in China, US-affiliated)', degree_level: 'Masters', field_of_study: 'Global Affairs, Public Policy, Business', amount: '75000', currency: 'USD', coverage: 'Full tuition, room, board, travel, personal stipend', deadline: 'September 15, 2026', eligibility: 'International applicants aged 18-28 with bachelor\'s degree', apply_url: 'https://schwarzmanscholars.org', description: 'Preparing future leaders to navigate the geopolitical landscape through a one-year master\'s programme.', is_full_ride: true },
    { name: 'Aga Khan Foundation International Scholarship', country: 'UK', university: 'Various Global Universities', degree_level: 'Masters', field_of_study: 'All Fields', amount: '30000', currency: 'USD', coverage: 'Tuition and living expenses on 50% grant, 50% loan basis', deadline: 'March 31, 2027', eligibility: 'Nationals of select developing countries with no alternative funding', apply_url: 'https://akdn.org/our-agencies/aga-khan-foundation/international-scholarship-programme', description: 'Supporting outstanding students from developing countries who have no other means of financing their studies.', is_full_ride: false },
    { name: 'ETH Zurich Excellence Masters Scholarships', country: 'Germany', university: 'ETH Zurich (Switzerland)', degree_level: 'Masters', field_of_study: 'Science, Engineering, Mathematics', amount: '22000', currency: 'USD', coverage: 'Tuition waiver and living costs grant per semester', deadline: 'December 15, 2026', eligibility: 'Outstanding international master\'s students with top 10% academic performance', apply_url: 'https://ethz.ch/students/en/studies/financial/scholarships/excellencescholarship.html', description: 'ETH Zurich\'s premier scholarship for the very best international master\'s applicants.', is_full_ride: true },
    { name: 'University of Auckland International Student Excellence Scholarship', country: 'Australia', university: 'University of Auckland (New Zealand)', degree_level: 'Bachelors', field_of_study: 'All Fields', amount: '10000', currency: 'USD', coverage: 'Contribution towards first-year tuition fees', deadline: 'Open year-round', eligibility: 'International students with strong academic records applying to undergraduate programmes', apply_url: 'https://auckland.ac.nz/en/study/scholarships-and-awards.html', description: 'Merit-based scholarship for incoming international undergraduate students.', is_full_ride: false },
    { name: 'Swedish Institute Scholarships for Global Professionals', country: 'Netherlands', university: 'Various Swedish Universities', degree_level: 'Masters', field_of_study: 'All Fields', amount: '20000', currency: 'USD', coverage: 'Full tuition, living allowance, travel grant, insurance', deadline: 'February 10, 2027', eligibility: 'Professionals from eligible countries with 3000+ hours work experience', apply_url: 'https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals', description: 'For global professionals who want to pursue a master\'s degree in Sweden.', is_full_ride: true },
    { name: 'Korean Government Scholarship Program (KGSP)', country: 'Japan', university: 'Various Korean Universities', degree_level: 'Masters', field_of_study: 'All Fields', amount: '20000', currency: 'USD', coverage: 'Full tuition, airfare, monthly allowance, Korean language training, medical insurance', deadline: 'Varies by embassy', eligibility: 'International students under 40 from countries with diplomatic ties to Korea', apply_url: 'https://studyinkorea.go.kr/en/sub/gks/allnew_invite.do', description: 'Fully funded programme including one year of Korean language training before degree studies.', is_full_ride: true },
  ];

  for (const s of scholarships) {
    await query(`
      INSERT INTO scholarships (name, country, university, degree_level, field_of_study, amount, currency, coverage, deadline, eligibility, apply_url, description, is_full_ride)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
      ON CONFLICT DO NOTHING
    `, [s.name, s.country, s.university, s.degree_level, s.field_of_study, s.amount, s.currency, s.coverage, s.deadline, s.eligibility, s.apply_url, s.description, s.is_full_ride]);
  }
  console.log(`  ✓ ${scholarships.length} scholarships seeded`);

  // ── Cost of Living ────────────────────────────────────────────────────────

  const cities = [
    { city: 'Lagos', country: 'Nigeria', rent_1br: 350, rent_3br: 800, groceries_monthly: 150, transport_monthly: 60, utilities_monthly: 50, internet_monthly: 25, dining_out: 8, healthcare_monthly: 30, avg_salary: 600, quality_of_life_score: 42, safety_score: 35 },
    { city: 'London', country: 'United Kingdom', rent_1br: 2200, rent_3br: 3800, groceries_monthly: 400, transport_monthly: 200, utilities_monthly: 220, internet_monthly: 40, dining_out: 25, healthcare_monthly: 0, avg_salary: 4200, quality_of_life_score: 78, safety_score: 72 },
    { city: 'Toronto', country: 'Canada', rent_1br: 1800, rent_3br: 3200, groceries_monthly: 350, transport_monthly: 130, utilities_monthly: 150, internet_monthly: 60, dining_out: 20, healthcare_monthly: 0, avg_salary: 3500, quality_of_life_score: 82, safety_score: 78 },
    { city: 'New York', country: 'United States', rent_1br: 3200, rent_3br: 5500, groceries_monthly: 450, transport_monthly: 130, utilities_monthly: 180, internet_monthly: 65, dining_out: 30, healthcare_monthly: 350, avg_salary: 5800, quality_of_life_score: 75, safety_score: 65 },
    { city: 'Berlin', country: 'Germany', rent_1br: 1100, rent_3br: 2000, groceries_monthly: 300, transport_monthly: 90, utilities_monthly: 250, internet_monthly: 35, dining_out: 15, healthcare_monthly: 110, avg_salary: 3200, quality_of_life_score: 83, safety_score: 80 },
    { city: 'Sydney', country: 'Australia', rent_1br: 2000, rent_3br: 3600, groceries_monthly: 400, transport_monthly: 150, utilities_monthly: 180, internet_monthly: 55, dining_out: 22, healthcare_monthly: 0, avg_salary: 4000, quality_of_life_score: 85, safety_score: 82 },
    { city: 'Dubai', country: 'United Arab Emirates', rent_1br: 1800, rent_3br: 3500, groceries_monthly: 350, transport_monthly: 100, utilities_monthly: 160, internet_monthly: 80, dining_out: 15, healthcare_monthly: 200, avg_salary: 4500, quality_of_life_score: 80, safety_score: 90 },
    { city: 'Tokyo', country: 'Japan', rent_1br: 1200, rent_3br: 2500, groceries_monthly: 350, transport_monthly: 100, utilities_monthly: 150, internet_monthly: 40, dining_out: 12, healthcare_monthly: 80, avg_salary: 3200, quality_of_life_score: 84, safety_score: 92 },
    { city: 'Paris', country: 'France', rent_1br: 1400, rent_3br: 2800, groceries_monthly: 380, transport_monthly: 80, utilities_monthly: 190, internet_monthly: 35, dining_out: 20, healthcare_monthly: 0, avg_salary: 3000, quality_of_life_score: 79, safety_score: 68 },
    { city: 'Amsterdam', country: 'Netherlands', rent_1br: 1600, rent_3br: 2800, groceries_monthly: 350, transport_monthly: 100, utilities_monthly: 200, internet_monthly: 45, dining_out: 20, healthcare_monthly: 130, avg_salary: 3600, quality_of_life_score: 86, safety_score: 82 },
    { city: 'Singapore', country: 'Singapore', rent_1br: 2200, rent_3br: 4000, groceries_monthly: 350, transport_monthly: 80, utilities_monthly: 120, internet_monthly: 35, dining_out: 10, healthcare_monthly: 100, avg_salary: 4800, quality_of_life_score: 88, safety_score: 95 },
    { city: 'Nairobi', country: 'Kenya', rent_1br: 400, rent_3br: 900, groceries_monthly: 180, transport_monthly: 50, utilities_monthly: 80, internet_monthly: 30, dining_out: 8, healthcare_monthly: 40, avg_salary: 700, quality_of_life_score: 48, safety_score: 40 },
    { city: 'Cape Town', country: 'South Africa', rent_1br: 550, rent_3br: 1200, groceries_monthly: 200, transport_monthly: 60, utilities_monthly: 90, internet_monthly: 35, dining_out: 10, healthcare_monthly: 60, avg_salary: 1200, quality_of_life_score: 62, safety_score: 38 },
    { city: 'Mumbai', country: 'India', rent_1br: 500, rent_3br: 1100, groceries_monthly: 120, transport_monthly: 30, utilities_monthly: 40, internet_monthly: 10, dining_out: 5, healthcare_monthly: 20, avg_salary: 800, quality_of_life_score: 50, safety_score: 52 },
    { city: 'Bangkok', country: 'Thailand', rent_1br: 500, rent_3br: 1000, groceries_monthly: 150, transport_monthly: 40, utilities_monthly: 60, internet_monthly: 20, dining_out: 5, healthcare_monthly: 30, avg_salary: 900, quality_of_life_score: 65, safety_score: 62 },
    { city: 'Istanbul', country: 'Turkey', rent_1br: 400, rent_3br: 800, groceries_monthly: 200, transport_monthly: 40, utilities_monthly: 60, internet_monthly: 15, dining_out: 8, healthcare_monthly: 25, avg_salary: 700, quality_of_life_score: 58, safety_score: 55 },
    { city: 'Madrid', country: 'Spain', rent_1br: 1000, rent_3br: 1800, groceries_monthly: 300, transport_monthly: 55, utilities_monthly: 140, internet_monthly: 35, dining_out: 15, healthcare_monthly: 0, avg_salary: 2400, quality_of_life_score: 80, safety_score: 78 },
    { city: 'Dublin', country: 'Ireland', rent_1br: 1900, rent_3br: 3200, groceries_monthly: 350, transport_monthly: 120, utilities_monthly: 200, internet_monthly: 55, dining_out: 22, healthcare_monthly: 50, avg_salary: 3800, quality_of_life_score: 81, safety_score: 80 },
    { city: 'Stockholm', country: 'Sweden', rent_1br: 1300, rent_3br: 2400, groceries_monthly: 350, transport_monthly: 100, utilities_monthly: 80, internet_monthly: 30, dining_out: 20, healthcare_monthly: 0, avg_salary: 3500, quality_of_life_score: 87, safety_score: 85 },
    { city: 'Oslo', country: 'Norway', rent_1br: 1500, rent_3br: 2700, groceries_monthly: 450, transport_monthly: 110, utilities_monthly: 180, internet_monthly: 50, dining_out: 30, healthcare_monthly: 0, avg_salary: 4500, quality_of_life_score: 88, safety_score: 88 },
    { city: 'Zurich', country: 'Switzerland', rent_1br: 2200, rent_3br: 3800, groceries_monthly: 500, transport_monthly: 120, utilities_monthly: 200, internet_monthly: 55, dining_out: 35, healthcare_monthly: 350, avg_salary: 6500, quality_of_life_score: 90, safety_score: 92 },
    { city: 'Auckland', country: 'New Zealand', rent_1br: 1300, rent_3br: 2400, groceries_monthly: 350, transport_monthly: 120, utilities_monthly: 150, internet_monthly: 55, dining_out: 18, healthcare_monthly: 0, avg_salary: 3000, quality_of_life_score: 84, safety_score: 85 },
    { city: 'Vancouver', country: 'Canada', rent_1br: 2000, rent_3br: 3500, groceries_monthly: 350, transport_monthly: 110, utilities_monthly: 120, internet_monthly: 60, dining_out: 20, healthcare_monthly: 0, avg_salary: 3400, quality_of_life_score: 83, safety_score: 80 },
    { city: 'San Francisco', country: 'United States', rent_1br: 3000, rent_3br: 5200, groceries_monthly: 450, transport_monthly: 100, utilities_monthly: 170, internet_monthly: 65, dining_out: 28, healthcare_monthly: 400, avg_salary: 6500, quality_of_life_score: 74, safety_score: 58 },
    { city: 'Chicago', country: 'United States', rent_1br: 1800, rent_3br: 3200, groceries_monthly: 350, transport_monthly: 110, utilities_monthly: 150, internet_monthly: 60, dining_out: 22, healthcare_monthly: 350, avg_salary: 4500, quality_of_life_score: 72, safety_score: 55 },
    { city: 'Manchester', country: 'United Kingdom', rent_1br: 1100, rent_3br: 1800, groceries_monthly: 300, transport_monthly: 90, utilities_monthly: 180, internet_monthly: 35, dining_out: 18, healthcare_monthly: 0, avg_salary: 3200, quality_of_life_score: 75, safety_score: 68 },
    { city: 'Melbourne', country: 'Australia', rent_1br: 1500, rent_3br: 2800, groceries_monthly: 380, transport_monthly: 120, utilities_monthly: 170, internet_monthly: 55, dining_out: 20, healthcare_monthly: 0, avg_salary: 3800, quality_of_life_score: 86, safety_score: 84 },
    { city: 'Seoul', country: 'South Korea', rent_1br: 800, rent_3br: 1800, groceries_monthly: 300, transport_monthly: 55, utilities_monthly: 100, internet_monthly: 25, dining_out: 10, healthcare_monthly: 50, avg_salary: 2800, quality_of_life_score: 78, safety_score: 88 },
    { city: 'Shanghai', country: 'China', rent_1br: 900, rent_3br: 1800, groceries_monthly: 250, transport_monthly: 40, utilities_monthly: 60, internet_monthly: 15, dining_out: 8, healthcare_monthly: 30, avg_salary: 1800, quality_of_life_score: 65, safety_score: 82 },
    { city: 'Accra', country: 'Ghana', rent_1br: 300, rent_3br: 700, groceries_monthly: 150, transport_monthly: 50, utilities_monthly: 60, internet_monthly: 30, dining_out: 6, healthcare_monthly: 25, avg_salary: 500, quality_of_life_score: 45, safety_score: 50 },
  ];

  for (const c of cities) {
    await query(`
      INSERT INTO cost_of_living (city, country, currency, rent_1br, rent_3br, groceries_monthly, transport_monthly, utilities_monthly, internet_monthly, dining_out, healthcare_monthly, avg_salary, quality_of_life_score, safety_score)
      VALUES ($1, $2, 'USD', $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
      ON CONFLICT (city, country) DO UPDATE SET
        rent_1br = EXCLUDED.rent_1br, rent_3br = EXCLUDED.rent_3br,
        groceries_monthly = EXCLUDED.groceries_monthly, transport_monthly = EXCLUDED.transport_monthly,
        utilities_monthly = EXCLUDED.utilities_monthly, internet_monthly = EXCLUDED.internet_monthly,
        dining_out = EXCLUDED.dining_out, healthcare_monthly = EXCLUDED.healthcare_monthly,
        avg_salary = EXCLUDED.avg_salary, quality_of_life_score = EXCLUDED.quality_of_life_score,
        safety_score = EXCLUDED.safety_score, updated_at = NOW()
    `, [c.city, c.country, c.rent_1br, c.rent_3br, c.groceries_monthly, c.transport_monthly, c.utilities_monthly, c.internet_monthly, c.dining_out, c.healthcare_monthly, c.avg_salary, c.quality_of_life_score, c.safety_score]);
  }
  console.log(`  ✓ ${cities.length} cities cost of living seeded`);

  console.log('✅ V10 seed complete!');
}

module.exports = seedV10;

if (require.main === module) {
  seedV10().then(() => process.exit(0)).catch(e => { console.error(e); process.exit(1); });
}
